language: csharp
solution: Plumb.Cacher.sln
script:
    - xbuild Plumb.Cacher.sln
    - mono ./packages/xunit.runner.console.2.2.0/tools/xunit.console.exe ./Tests/bin/Debug/Tests.dll
    - BuildNugetPackage.sh